#!/bin/bash

# Installs contents of this repo.
LOG=~/deploy_dsa110-pyutils.log
DATE="`date --iso-8601='seconds'`"
echo "$DATE: `which python`" > $LOG
output=`pip install .`
echo "$DATE: $output" >> $LOG
